## class

### Inheritance

In [1]:
class base(object):
    pass
class inher(base):
    pass

## numpy

In [2]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 6.11 ms, sys: 22.4 ms, total: 28.6 ms
Wall time: 47.6 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 303 ms, sys: 213 ms, total: 515 ms
Wall time: 523 ms


In [5]:
data = np.random.randn(2, 3)

In [6]:
data

array([[-0.70086995, -1.36899674, -1.25278522],
       [-0.57075368, -0.04046724,  0.40846108]])

In [7]:
data

array([[-0.70086995, -1.36899674, -1.25278522],
       [-0.57075368, -0.04046724,  0.40846108]])

In [8]:
data * 10

array([[ -7.00869954, -13.68996737, -12.52785216],
       [ -5.70753684,  -0.40467244,   4.08461084]])

### NumPy: ndarray